# Generated by Django 4.1.2 on 2022-10-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.URLField(blank=True, null=True),
        ),
    ]
