# Generated by Django 4.1.2 on 2022-10-27 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_usertype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="key_skills",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="speciality",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="useful_to_project",
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.usertype",
            ),
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_skills", models.CharField(blank=True, max_length=255)),
                ("useful_to_project", models.CharField(blank=True, max_length=255)),
                ("speciality", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
