# Generated by Django 4.1.2 on 2022-10-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_managers_customuser_about_me_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="photo_address",
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="uploads/users_avatars/"),
        ),
    ]
