# Generated by Django 4.1.2 on 2022-11-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_expert_user_alter_investor_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="additional_role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Ментор"), (3, "Эксперт"), (4, "Инвестор")], null=True
            ),
        ),
        migrations.AddField(
            model_name="investor",
            name="additional_role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Ментор"), (3, "Эксперт"), (4, "Инвестор")], null=True
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="additional_role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Ментор"), (3, "Эксперт"), (4, "Инвестор")], null=True
            ),
        ),
    ]
