# Generated by Django 4.1.2 on 2022-11-06 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("industries", "0001_initial"),
        ("users", "0011_expert_additional_role_investor_additional_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="speciality",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="job",
        ),
        migrations.AddField(
            model_name="customuser",
            name="datetime_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="preferred_industries",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="industries.industry"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="key_skills",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
