# Generated by Django 4.1.2 on 2022-11-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_member_speciality_remove_mentor_job_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expert",
            old_name="additional_role",
            new_name="first_additional_role",
        ),
        migrations.RenameField(
            model_name="investor",
            old_name="additional_role",
            new_name="first_additional_role",
        ),
        migrations.RenameField(
            model_name="mentor",
            old_name="additional_role",
            new_name="first_additional_role",
        ),
        migrations.AddField(
            model_name="expert",
            name="second_additional_role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Ментор"), (3, "Эксперт"), (4, "Инвестор")], null=True
            ),
        ),
        migrations.AddField(
            model_name="investor",
            name="second_additional_role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Ментор"), (3, "Эксперт"), (4, "Инвестор")], null=True
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="second_additional_role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Ментор"), (3, "Эксперт"), (4, "Инвестор")], null=True
            ),
        ),
    ]
