# Generated by Django 4.1.2 on 2022-11-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_rename_additional_role_expert_first_additional_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
