# Generated by Django 4.1.2 on 2022-11-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_customuser_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="speciality",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
