# Generated by Django 4.1.3 on 2022-11-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_customuser_city_alter_customuser_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="about_me",
            field=models.TextField(blank=True, null=True),
        ),
    ]
