# Generated by Django 4.1.3 on 2022-11-18 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_userachievement_user_to_not_null(apps, schema_editor):
    UserAchievement = apps.get_model('users', 'UserAchievement')
    User = apps.get_model('users', 'CustomUser')
    legend = User.objects.all()[0]
    for u in UserAchievement.objects.filter(user=None):
        u.user = legend
        u.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_customuser_about_me"),
    ]

    operations = [
        migrations.RunPython(set_userachievement_user_to_not_null),
        migrations.AlterField(
            model_name="userachievement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
