# Generated by Django 4.1.3 on 2022-11-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_userachievement_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="key_skills",
        ),
        migrations.AddField(
            model_name="customuser",
            name="key_skills",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
