# Generated by Django 4.1.3 on 2022-11-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_remove_member_key_skills_customuser_key_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="key_skills",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
