# Generated by Django 4.1.3 on 2022-11-23 12:43

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_alter_customuser_key_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Участник"), (2, "Ментор"), (3, "Эксперт"), (4, "Инвестор")],
                default=users.models.get_default_user_type,
            ),
        ),
        migrations.RemoveField(
            model_name="expert",
            name="preferred_industries",
        ),
        migrations.RemoveField(
            model_name="investor",
            name="preferred_industries",
        ),
        migrations.AddField(
            model_name="expert",
            name="preferred_industries",
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name="investor",
            name="preferred_industries",
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
