# Generated by Django 4.1.3 on 2022-12-11 14:17

import datetime
from django.db import migrations, models
import django.db.models.expressions


def set_birthday_defaults(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    for user in CustomUser.objects.all():
        if not user.birthday:
            user.birthday = "2000-01-01"
            user.save()


def rev(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_alter_customuser_user_type_and_more"),
    ]

    operations = [
        migrations.RunPython(set_birthday_defaults, rev),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birthday",
            field=models.DateField(null=False, default="2000-01-01"),
        ),
    ]
