# Generated by Django 4.1.3 on 2022-12-11 14:17

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_alter_customuser_user_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birthday",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "birthday__lte",
                        django.db.models.expressions.CombinedExpression(
                            models.F("birthday"),
                            "-",
                            models.Value(datetime.timedelta(days=5110)),
                        ),
                    )
                ),
                name="user_birthday_constraint",
            ),
        ),
    ]
