# Generated by Django 4.1.3 on 2022-12-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_alter_customuser_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="preferred_industries",
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
