# Generated by Django 4.1.3 on 2022-12-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_mentor_preferred_industries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="preferred_industries",
        ),
        migrations.AlterField(
            model_name="expert",
            name="preferred_industries",
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name="investor",
            name="preferred_industries",
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="preferred_industries",
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
