# Generated by Django 4.1.3 on 2023-01-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_likesonproject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="likesonproject",
            old_name="like",
            new_name="is_liked",
        ),
    ]
