# Generated by Django 4.1.3 on 2023-04-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_rename_like_likesonproject_is_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="onboarding_stage",
            field=models.PositiveSmallIntegerField(null=True, blank=True),
        ),
    ]
