# Generated by Django 4.1.3 on 2023-04-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_customuser_onboarding_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="onboarding_stage",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
