# Generated by Django 4.1.3 on 2023-04-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_alter_customuser_onboarding_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="onboarding_stage",
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
