# Generated by Django 4.1.3 on 2023-04-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_alter_customuser_onboarding_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verification_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата верификации"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="onboarding_stage",
            field=models.PositiveSmallIntegerField(
                blank=True,
                editable=False,
                help_text="null(пустое) - онбординг пройден, 1, 2 и 3 - номера стадий онбординга",
                null=True,
                verbose_name="Стадия онбординга",
            ),
        ),
    ]
