# Generated by Django 4.1.3 on 2023-05-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_alter_customuser_onboarding_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="onboarding_stage",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                editable=False,
                help_text="0, 1, 2 - номера стадий онбординга, null(пустое) - онбординг пройден",
                null=True,
                verbose_name="Стадия онбординга",
            ),
        ),
    ]
