# Generated by Django 4.2.3 on 2023-07-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_userlink"),
    ]

    operations = []
