# Generated by Django 4.2.3 on 2023-07-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_auto_20230713_0023"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-ordering_score"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="ordering_score",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
