# Generated by Django 4.2.3 on 2023-08-08 19:56

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0038_alter_customuser_options_customuser_ordering_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                max_length=255, validators=[users.validators.user_name_validator]
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                max_length=255, validators=[users.validators.user_name_validator]
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="patronymic",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[users.validators.user_name_validator],
            ),
        ),
    ]
