# Generated by Django 4.2.3 on 2023-08-10 11:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Участник"),
                    (2, "Ментор"),
                    (3, "Консультант"),
                    (4, "Инвестор"),
                ],
                default=users.models.get_default_user_type,
            ),
        ),
        migrations.AlterField(
            model_name="expert",
            name="first_additional_role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Ментор"), (3, "Консультант"), (4, "Инвестор")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="expert",
            name="second_additional_role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Ментор"), (3, "Консультант"), (4, "Инвестор")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="investor",
            name="first_additional_role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Ментор"), (3, "Консультант"), (4, "Инвестор")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="investor",
            name="second_additional_role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Ментор"), (3, "Консультант"), (4, "Инвестор")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="first_additional_role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Ментор"), (3, "Консультант"), (4, "Инвестор")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="second_additional_role",
            field=models.PositiveSmallIntegerField(
                choices=[(2, "Ментор"), (3, "Консультант"), (4, "Инвестор")], null=True
            ),
        ),
    ]
