# Generated by Django 4.2.3 on 2023-10-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_alter_customuser_user_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-ordering_score", "id"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
