# Generated by Django 4.2.3 on 2023-12-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expert",
            options={"verbose_name": "Эксперт", "verbose_name_plural": "Эксперты"},
        ),
        migrations.AlterModelOptions(
            name="investor",
            options={"verbose_name": "Инвестор", "verbose_name_plural": "Инвесторы"},
        ),
        migrations.AlterModelOptions(
            name="member",
            options={"verbose_name": "Участник", "verbose_name_plural": "Участники"},
        ),
        migrations.AlterModelOptions(
            name="mentor",
            options={"verbose_name": "Ментор", "verbose_name_plural": "Менторы"},
        ),
    ]
