# Generated by Django 4.2.3 on 2024-01-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auto_20231223_1331"),
        ("users", "0042_alter_expert_options_alter_investor_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="v2_speciality",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.specialization",
            ),
        ),
    ]
