# Generated by Django 4.2.3 on 2024-01-28 19:36
from django.contrib.auth import get_user_model
from django.db import migrations

from core.models import Specialization
from users.models import CustomUser

User = get_user_model()


def migrate_specializations(apps, schema_editor):
    specializations = Specialization.objects.all()

    for user in User.objects.all():
        if user.speciality:
            user.v2_speciality = guess_speciality(user.speciality, specializations)
            user.save()


def guess_speciality(speciality, specializations):
    normalized_speciality = normalize(speciality)
    for specialization in specializations:
        if normalized_speciality == normalize(specialization.name):
            return specialization

    for specialization in specializations:
        if normalized_speciality in normalize(specialization.name):
            return specialization


def normalize(string: str) -> str:
    return string.lower().replace(" ", "").replace("-", "")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0043_customuser_v2_speciality"),
    ]

    operations = [
        migrations.RunPython(migrate_specializations, reverse_code=migrations.RunPython.noop),
    ]
