# Generated by Django 4.2.3 on 2024-02-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_programs", "0004_auto_20231230_0002"),
        ("users", "0044_auto_20240128_2236"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="programs",
            field=models.ManyToManyField(
                related_name="experts", to="partner_programs.partnerprogram"
            ),
        ),
    ]

