# Generated by Django 4.2.3 on 2024-02-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_specialization_options_and_more"),
        ("users", "0044_auto_20240128_2236"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="v2_speciality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.specialization",
            ),
        ),
    ]
