# Generated by Django 4.2.3 on 2024-03-01 12:31

from django.db import migrations


def migrate(apps, schema_editor):
    try:
        migrations.RemoveConstraint(
            model_name='customuser',
            name='users_customuser_v2_speciality_id_key',
        )
    except ValueError as e:
        if "No constraint named users_customuser_v2_speciality_id_key" in str(e):
            pass
        else:
            raise


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0046_expert_programs"),
    ]

    operations = [
        migrations.RunPython(migrate),
    ]
