# Generated by Django 4.2.11 on 2024-10-08 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0050_userskillconfirmation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usereducation",
            options={
                "verbose_name": "Образование пользователя",
                "verbose_name_plural": "Образование пользователя",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Пример: +7 XXX XX-XX-XX | +7XXXXXXXXX | +7 (XXX) XX-XX-XX",
                max_length=20,
                null=True,
                validators=[users.validators.user_phone_number_validation],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AddField(
            model_name="usereducation",
            name="completion_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[users.validators.user_experience_years_range_validator],
                verbose_name="Год завершения",
            ),
        ),
        migrations.AddField(
            model_name="usereducation",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Среднее общее образование", "Среднее общее образование"),
                    (
                        "Среднее профессиональное образование",
                        "Среднее профессиональное образование",
                    ),
                    (
                        "Высшее образование – бакалавриат, специалитет",
                        "Высшее образование – бакалавриат, специалитет",
                    ),
                    (
                        "Высшее образование – магистратура",
                        "Высшее образование – магистратура",
                    ),
                    (
                        "Высшее образование – аспирантура",
                        "Высшее образование – аспирантура",
                    ),
                ],
                max_length=256,
                null=True,
                verbose_name="Уровень образования",
            ),
        ),
        migrations.AddField(
            model_name="usereducation",
            name="education_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ученик", "Ученик"),
                    ("Студент", "Студент"),
                    ("Выпускник", "Выпускник"),
                ],
                max_length=256,
                null=True,
                verbose_name="Статус по обучению",
            ),
        ),
        migrations.AlterField(
            model_name="usereducation",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Краткое описание"
            ),
        ),
        migrations.AlterField(
            model_name="usereducation",
            name="entry_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[users.validators.user_experience_years_range_validator],
                verbose_name="Год начала",
            ),
        ),
        migrations.CreateModel(
            name="UserWorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование организации"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "entry_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            users.validators.user_experience_years_range_validator
                        ],
                        verbose_name="Год начала",
                    ),
                ),
                (
                    "completion_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            users.validators.user_experience_years_range_validator
                        ],
                        verbose_name="Год завершения",
                    ),
                ),
                (
                    "job_position",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experience",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа пользователя",
                "verbose_name_plural": "Работа пользователя",
            },
        ),
        migrations.CreateModel(
            name="UserLanguages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("Английский", "Английский"),
                            ("Испанский", "Испанский"),
                            ("Итальянский", "Итальянский"),
                            ("Немецкий", "Немецкий"),
                            ("Японский", "Японский"),
                            ("Китайский", "Китайский"),
                            ("Арабский", "Арабский"),
                            ("Шведский", "Шведский"),
                            ("Польский", "Польский"),
                            ("Чешский", "Чешский"),
                            ("Русский", "Русский"),
                            ("Французский", "Французский"),
                        ],
                        max_length=50,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "language_level",
                    models.CharField(
                        choices=[
                            ("А1", "А1"),
                            ("А2", "А2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("С1", "С1"),
                            ("С2", "С2"),
                        ],
                        max_length=50,
                        verbose_name="Уровнь владения",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_languages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Знание языка",
                "verbose_name_plural": "Знание языков",
            },
        ),
        migrations.AddConstraint(
            model_name="userlanguages",
            constraint=models.UniqueConstraint(
                fields=("user", "language"),
                name="unique_user_language",
                violation_error_message="Нельзя добавлять дубликаты языков",
            ),
        ),
    ]
