# Generated by Django 4.2.11 on 2024-10-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0051_alter_usereducation_options_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="organization",
        ),
    ]
