# Generated by Django 4.2.11 on 2025-07-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0052_remove_customuser_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_mospolytech_student",
            field=models.BooleanField(
                default=False,
                help_text="Флаг, указывающий, является ли пользователь студентом МосПолитеха",
                verbose_name="Студент Московского Политеха",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="study_group",
            field=models.CharField(
                blank=True,
                help_text="Краткое обозначение учебной группы (до 10 символов)",
                max_length=10,
                null=True,
                verbose_name="Учебная группа",
            ),
        ),
    ]
