# Generated by Django 4.2.11 on 2025-08-20 07:55

from django.db import migrations, models
import functools
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0053_customuser_is_mospolytech_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                max_length=255,
                validators=[
                    functools.partial(
                        users.validators.user_name_validator, *(), **{"field_name": "Имя"}
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                max_length=255,
                validators=[
                    functools.partial(
                        users.validators.user_name_validator,
                        *(),
                        **{"field_name": "Фамилия"}
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="patronymic",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    functools.partial(
                        users.validators.user_name_validator,
                        *(),
                        **{"field_name": "Отчество"}
                    )
                ],
            ),
        ),
    ]
