# Generated by Django 4.2.11 on 2025-09-02 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0054_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.URLValidator(message="Введите корректный URL")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Пользователь с таким email уже существует"},
                max_length=254,
                unique=True,
            ),
        ),
    ]
