# Generated by Django 4.2.24 on 2025-10-20 08:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0007_auto_20230929_1727"),
        ("users", "0055_alter_customuser_avatar_alter_customuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAchievementFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл достижения",
                "verbose_name_plural": "Файлы достижения",
            },
        ),
        migrations.AddField(
            model_name="userachievement",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2025),
                ],
                verbose_name="Год достижения",
            ),
        ),
        migrations.AddConstraint(
            model_name="userachievement",
            constraint=models.UniqueConstraint(
                fields=("user", "title", "year"), name="uniq_user_achievement_title_year"
            ),
        ),
        migrations.AddField(
            model_name="userachievementfile",
            name="achievement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="users.userachievement",
                verbose_name="Достижение",
            ),
        ),
        migrations.AddField(
            model_name="userachievementfile",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievement_links",
                to="files.userfile",
                verbose_name="Файл",
            ),
        ),
        migrations.AddConstraint(
            model_name="userachievementfile",
            constraint=models.UniqueConstraint(
                fields=("achievement", "file"), name="uniq_achievement_file_link"
            ),
        ),
    ]
