# Generated by Django 4.2.24 on 2025-10-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0056_userachievementfile_userachievement_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usereducation",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Направление обучения",
            ),
        ),
        migrations.AlterField(
            model_name="userworkexperience",
            name="description",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Краткое описание деятельности",
            ),
        ),
    ]
