# Generated by Django 4.2.24 on 2025-10-24 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0007_auto_20230929_1727"),
        ("users", "0057_alter_usereducation_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userachievement",
            name="files",
            field=models.ManyToManyField(
                blank=True,
                related_name="achievements",
                related_query_name="achievement",
                through="users.UserAchievementFile",
                to="files.userfile",
            ),
        ),
        migrations.AlterField(
            model_name="userachievementfile",
            name="achievement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_links",
                related_query_name="file_link",
                to="users.userachievement",
                verbose_name="Достижение",
            ),
        ),
        migrations.AlterField(
            model_name="userachievementfile",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievement_links",
                related_query_name="achievement_link",
                to="files.userfile",
                verbose_name="Файл",
            ),
        ),
    ]
