# Generated by Django 4.2.24 on 2026-02-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0058_userachievement_files_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_activity",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Последняя активность",
            ),
        ),
    ]
