# Generated by Django 4.2.11 on 2026-02-09 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0059_customuser_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userachievement",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2026),
                ],
                verbose_name="Год достижения",
            ),
        ),
    ]
