# Generated by Django 4.2.11 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0060_alter_userachievement_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlink",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("telegram", "Telegram"),
                    ("vk", "ВКонтакте"),
                    ("github", "GitHub"),
                    ("linkedin", "LinkedIn"),
                    ("website", "Сайт"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="userlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind__isnull", False)),
                fields=("user", "kind"),
                name="unique_typed_user_link_kind",
            ),
        ),
    ]
