# Generated by Django 4.2.11 on 2026-10-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0061_customuser_modal_acknowledgements"),
    ]

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название для выбора"),
                ),
                (
                    "full_name",
                    models.TextField(
                        blank=True, verbose_name="Полное официальное название"
                    ),
                ),
                (
                    "aliases",
                    models.TextField(
                        blank=True,
                        help_text="Например: МГУ, МГУ имени Ломоносова. Используются при поиске.",
                        verbose_name="Сокращения и другие названия",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Показывать в списке"),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Код в источнике",
                    ),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="Источник")),
                (
                    "source_checked_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата проверки источника"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                ("search_text", models.TextField(blank=True, editable=False)),
            ],
            options={
                "verbose_name": "Вуз (справочник)",
                "verbose_name_plural": "Вузы (справочник)",
                "ordering": ("name", "city", "id"),
            },
        ),
    ]
