# Generated by Django 4.1.3 on 2023-03-22 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('short_text', models.TextField(blank=True, help_text='Текст для поста в телеграм', max_length=256)),
                ('cover_url', models.URLField()),
                ('datetime_of_event', models.DateTimeField(verbose_name='Дата проведения')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('tg_message_id', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField()),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Оффлайн'), (1, 'Онлайн'), (2, 'Оффлайн и онлайн')])),
                ('prize', models.CharField(max_length=128)),
                ('views', models.BigIntegerField(default=0)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('registered_users', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
