# Generated by Django 4.1.3 on 2023-03-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_tg_message_id"),
    ]

    operations = []
