# Generated by Django 4.1.3 on 2023-03-22 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0005_auto_20230323_0032"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Оффлайн"), (1, "Онлайн"), (2, "Оффлайн и онлайн")],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorites", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="prize",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registered_users",
            field=models.ManyToManyField(
                blank=True, related_name="events", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="views",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="website_url",
            field=models.URLField(default="https://procollab.ru"),
        ),
        migrations.AlterField(
            model_name="event",
            name="short_text",
            field=models.TextField(
                blank=True, help_text="Текст для поста в телеграм", max_length=256
            ),
        ),
    ]
