# Generated by Django 4.1.3 on 2023-03-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_tg_message_id"),
        ("events", "0007_event_tags"),
    ]

    operations = []
