# Generated by Django 4.1.3 on 2023-04-03 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0009_alter_event_datetime_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="short_text",
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="event",
            name="tg_message_id",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="views",
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
