# Generated by Django 4.2.3 on 2023-09-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_mailingschema_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingschema",
            name="schema",
            field=models.JSONField(blank=True, default="", null=True),
        ),
    ]
