# Generated by Django 4.2.3 on 2023-10-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_mailingschema_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingschema",
            name="schema",
            field=models.JSONField(
                blank=True,
                default={
                    "default_key": {"title": "Просто ключ."},
                    "key_with_default_value": {
                        "default": "Значение",
                        "title": "Ключ с стандартным значением.",
                    },
                },
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mailingschema",
            name="template",
            field=models.TextField(),
        ),
    ]
