# Generated by Django 4.2.11 on 2026-02-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_mailing_scenario_log"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mailingscenariolog",
            new_name="mailing_mai_scenari_eed98a_idx",
            old_name="mailing_ma_scenari_73b1f9_idx",
        ),
        migrations.RenameIndex(
            model_name="mailingscenariolog",
            new_name="mailing_mai_program_63bc97_idx",
            old_name="mailing_ma_program_b9dcf9_idx",
        ),
        migrations.RenameIndex(
            model_name="mailingscenariolog",
            new_name="mailing_mai_user_id_333e66_idx",
            old_name="mailing_ma_user_id_0e2a92_idx",
        ),
    ]
