# Generated by Django 4.1.2 on 2022-10-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("industries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="industry",
            options={"verbose_name": "Индустрия", "verbose_name_plural": "Индустрии"},
        ),
    ]
