# Generated by Django 4.1.3 on 2022-12-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("industries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="industry",
            options={
                "ordering": ["name"],
                "verbose_name": "Индустрия",
                "verbose_name_plural": "Индустрии",
            },
        ),
    ]
