# Generated by Django 4.1.2 on 2022-10-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("status", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name": "Достижение",
                "verbose_name_plural": "Достижения",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True)),
                ("short_description", models.TextField(blank=True)),
                ("region", models.CharField(blank=True, max_length=256)),
                (
                    "step",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Идея"),
                            (1, "Прототип"),
                            (2, "MVP(Минимально жизнеспособный продукт)"),
                            (3, "Первые продажи"),
                            (4, "Масштабирование"),
                        ]
                    ),
                ),
                ("presentation_address", models.URLField(blank=True)),
                ("image_address", models.URLField(blank=True)),
                ("draft", models.BooleanField(default=True)),
                (
                    "datetime_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
    ]
