# Generated by Django 4.1.2 on 2022-10-19 21:53

from django.db import migrations, models
import projects.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="achievements",
            field=models.JSONField(default=projects.helpers.get_default_achievements),
        ),
    ]
