# Generated by Django 4.1.2 on 2022-10-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image_address",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="presentation_address",
            field=models.URLField(blank=True),
        ),
    ]
