# Generated by Django 4.1.2 on 2022-10-23 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_alter_project_image_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
