# Generated by Django 4.1.2 on 2022-11-05 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0004_collaborator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="collaborators",
        ),
        migrations.AddField(
            model_name="project",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="projects",
                through="projects.Collaborator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="collaborator",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="unique_collaorator"
            ),
        ),
    ]
