# Generated by Django 4.1.2 on 2022-11-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_collaborator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="collaborators",
        ),
    ]
