# Generated by Django 4.1.2 on 2022-11-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_collaborators_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="step",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Идея"),
                    (1, "Прототип"),
                    (2, "MVP(Минимально жизнеспособный продукт)"),
                    (3, "Первые продажи"),
                    (4, "Масштабирование"),
                ],
                null=True,
            ),
        ),
    ]
