# Generated by Django 4.1.3 on 2022-11-18 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_userachievement_user_to_not_null(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Project.objects.filter(leader=None).delete()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("industries", "0001_initial"),
        ("projects", "0007_remove_collaborator_unique_collaorator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="image_address",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="industries.industry",
            ),
        ),
        migrations.RunPython(set_userachievement_user_to_not_null),
        migrations.AlterField(
            model_name="project",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaders_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="presentation_address",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="region",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
