# Generated by Django 4.1.3 on 2022-11-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_project_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="short_description",
        ),
    ]
