# Generated by Django 4.1.3 on 2023-01-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_collaborator_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
