# Generated by Django 4.2 on 2023-06-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_projectnews"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectnews",
            options={
                "verbose_name": "Новость проекта",
                "verbose_name_plural": "Новости проекта",
            },
        ),
        migrations.RemoveField(
            model_name="projectnews",
            name="views_count",
        ),
    ]
