# Generated by Django 4.1.3 on 2023-06-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_alter_projectnews_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="views_count",
        ),
    ]
