# Generated by Django 4.1.3 on 2023-06-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_userfile_extension_userfile_name_userfile_size"),
        ("projects", "0016_alter_projectnews_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cover",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_cover",
                to="files.userfile",
            ),
        ),
        migrations.CreateModel(
            name="DefaultProjectCover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_covers",
                        to="files.userfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обложка проекта",
                "verbose_name_plural": "Обложки проектов",
            },
        ),
    ]
