# Generated by Django 4.1.3 on 2023-06-20 21:39

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_userfile_extension_userfile_name_userfile_size"),
        ("projects", "0017_project_cover_defaultprojectcover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cover",
            field=models.ForeignKey(
                default=projects.models.DefaultProjectCover.get_random_file,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="project_cover",
                to="files.userfile",
            ),
        ),
    ]
