# Generated by Django 4.1.3 on 2023-06-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_userfile_extension_userfile_name_userfile_size"),
        ("projects", "0017_project_cover_defaultprojectcover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultprojectcover",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_covers",
                to="files.userfile",
            ),
        ),

    ]
