# Generated by Django 4.2 on 2023-06-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_remove_project_views_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectnews",
            options={
                "ordering": ["-datetime_created"],
                "verbose_name": "Новость проекта",
                "verbose_name_plural": "Новости проекта",
            },
        ),
    ]
