# Generated by Django 4.1.3 on 2023-07-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_alter_projectnews_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-hidden_score", "-datetime_created"],
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="hidden_score",
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
