# Generated by Django 4.1.3 on 2023-06-27 11:46
import django
from django.db import migrations, models
import projects.models


def create_default_project_cover(apps, schema_editor):
    # create a random default cover using a random UserFile
    DefaultProjectCover = apps.get_model("projects", "DefaultProjectCover")
    default_cover = DefaultProjectCover.objects.create()
    # project = apps.get_model("projects", "Project")
    # project.objects.update(cover=default_cover.image)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_alter_defaultprojectcover_image_alter_project_cover"),
    ]

    operations = [
        migrations.RunPython(create_default_project_cover),
        migrations.AlterField(
            model_name="project",
            name="cover",
            field=models.ForeignKey(
                default=projects.models.DefaultProjectCover.get_random_file,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="project_cover",
                to="files.userfile",
                null=True,
                blank=True
            ),
        ),
    ]
