# Generated by Django 4.2.3 on 2023-09-07 07:13

from django.db import migrations, models
import django.db.models.deletion
import projects.models

# Generated by Django 4.1.3 on 2023-06-27 11:46
import django
from django.db import migrations, models
import projects.models


def create_default_project_cover(apps, schema_editor):
    # create a random default cover using a random UserFile
    DefaultProjectCover = apps.get_model("projects", "DefaultProjectCover")
    default_cover = DefaultProjectCover.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_alter_defaultprojectcover_image_alter_project_cover"),
    ]

    operations = [
        migrations.RunPython(create_default_project_cover),
        migrations.AlterField(
            model_name="project",
            name="cover",
            field=models.ForeignKey(
                default=projects.models.DefaultProjectCover.get_random_file,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="project_cover",
                to="files.userfile",
                null=True,
                blank=True
            ),
        ),
    ]

class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_alter_userfile_options"),
        ("projects", "0019_alter_project_options_project_hidden_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultProjectCover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_covers",
                        to="files.userfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обложка проекта",
                "verbose_name_plural": "Обложки проектов",
            },
        ),
        migrations.RunPython(create_default_project_cover),
        migrations.AddField(
            model_name="project",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                default=projects.models.DefaultProjectCover.get_random_file,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="project_cover",
                to="files.userfile",
            ),
        ),
    ]
