# Generated by Django 4.2.11 on 2024-08-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_project_subscribers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-is_company", "-hidden_score", "-datetime_created"],
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="is_company",
            field=models.BooleanField(default=False),
        ),
    ]
