# Generated by Django 4.2.3 on 2023-12-16 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0021_project_subscribers"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=256)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="skills", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык пользователя",
                "verbose_name_plural": "Навыки пользователя",
                "ordering": ["skill"],
            },
        ),
        migrations.CreateModel(
            name="UserSkillTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_tag", models.CharField(max_length=256)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="projects.userskill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тег навыка пользователя",
                "verbose_name_plural": "Теги навыков пользователя",
                "ordering": ["skill_tag"],
            },
        ),
    ]
