# Generated by Django 4.2.3 on 2023-12-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_userskill_userskilltag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userskilltag",
            name="skill",
        ),
        migrations.DeleteModel(
            name="UserSkill",
        ),
        migrations.DeleteModel(
            name="UserSkillTag",
        ),
    ]
