# Generated by Django 4.2.11 on 2025-07-03 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_project_cover_image_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="actuality",
            field=models.TextField(
                blank=True,
                help_text="Почему проект важен (до 1000\u202fсимв.)",
                null=True,
                validators=[django.core.validators.MaxLengthValidator(1000)],
                verbose_name="Актуальность",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="direction",
            field=models.CharField(
                blank=True,
                help_text="Более общее направление деятельности проекта",
                max_length=256,
                null=True,
                verbose_name="Направление",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="goal",
            field=models.CharField(
                blank=True,
                help_text="Главная цель проекта (до 500\u202fсимв.)",
                max_length=500,
                null=True,
                verbose_name="Цель",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="problem",
            field=models.TextField(
                blank=True,
                help_text="Какую проблему решает проект (до 1000\u202fсимв.)",
                null=True,
                validators=[django.core.validators.MaxLengthValidator(1000)],
                verbose_name="Проблема",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="specialty",
            field=models.CharField(
                blank=True,
                help_text="Специализация проекта",
                max_length=256,
                null=True,
                verbose_name="Специальность",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="track",
            field=models.CharField(
                blank=True,
                help_text="Направление/курс, в рамках которого реализуется проект",
                max_length=256,
                null=True,
                verbose_name="Трек",
            ),
        ),
    ]
