# Generated by Django 4.2.11 on 2025-07-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_project_actuality_project_direction_project_goal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="specialty",
        ),
    ]
