# Generated by Django 4.2.11 on 2025-07-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_remove_project_specialty"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborator",
            name="specialization",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Направления работы участника в рамках проекта",
                max_length=100,
                null=True,
                verbose_name="Специализация",
            ),
        ),
    ]
