# Generated by Django 4.2.11 on 2025-07-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0007_auto_20230929_1727"),
        ("projects", "0026_collaborator_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defaultprojectcover",
            name="datetime_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="defaultprojectcover",
            name="datetime_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="defaultprojectcover",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="files.userfile",
            ),
        ),
        migrations.CreateModel(
            name="DefaultProjectAvatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="files.userfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аватарка проекта",
                "verbose_name_plural": "Аватарки проектов",
            },
        ),
    ]
