# Generated by Django 4.2.11 on 2025-09-02 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_alter_defaultprojectcover_datetime_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="direction",
        ),
        migrations.RemoveField(
            model_name="project",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="project",
            name="step",
        ),
        migrations.RemoveField(
            model_name="project",
            name="track",
        ),
        migrations.AddField(
            model_name="project",
            name="implementation_deadline",
            field=models.DateField(
                blank=True,
                help_text="Дата, до которой планируется реализовать проект",
                null=True,
                verbose_name="Общий срок реализации проекта",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="target_audience",
            field=models.CharField(
                blank=True,
                help_text="Описание целевой аудитории проекта (до 500 симв.)",
                max_length=500,
                null=True,
                verbose_name="Целевая аудитория",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="trl",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Technology Readiness Level (от 1 до 9)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ],
                verbose_name="TRL",
            ),
        ),
    ]
