# Generated by Django 4.2.11 on 2025-09-08 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0028_remove_project_direction_remove_project_goal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название цели")),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Срок реализации цели"
                    ),
                ),
                ("is_done", models.BooleanField(default=False, verbose_name="Выполнено")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsible_goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цель",
                "verbose_name_plural": "Цели",
            },
        ),
    ]
