# Generated by Django 4.2.24 on 2025-10-06 09:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0029_projectgoal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "inn",
                    models.CharField(
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ИНН должен содержать 10 или 12 цифр.",
                                regex="^\\d{10}(\\d{2})?$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Компания",
                "verbose_name_plural": "Компании",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("infrastructure", "Инфраструктурный"),
                            ("staff", "Кадровый"),
                            ("financial", "Финансовый"),
                            ("information", "Информационный"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "partner_company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если не указано — ресурс в поиске партнёра.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="projects.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресурс",
                "verbose_name_plural": "Ресурсы",
                "ordering": ["project", "type", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contribution", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_links",
                        to="projects.company",
                    ),
                ),
                (
                    "decision_maker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_companies",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь проекта и компании",
                "verbose_name_plural": "Связи проекта и компании",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="companies",
            field=models.ManyToManyField(
                related_name="projects",
                through="projects.ProjectCompany",
                to="projects.company",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectcompany",
            constraint=models.UniqueConstraint(
                fields=("project", "company"), name="uq_project_company_unique_pair"
            ),
        ),
    ]
