# Generated by Codex CLI on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_company_resource_projectcompany_project_companies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Если выключено — проект скрыт из общего каталога и ленты.",
                verbose_name="Публичный",
            ),
        ),
    ]

