# Generated by Django 4.2.11 on 2025-12-19

from django.db import migrations


def hide_program_projects(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    PartnerProgramProject = apps.get_model("partner_programs", "PartnerProgramProject")
    PartnerProgramUserProfile = apps.get_model(
        "partner_programs", "PartnerProgramUserProfile"
    )

    project_ids_from_links = PartnerProgramProject.objects.values_list(
        "project_id", flat=True
    ).exclude(project_id__isnull=True)
    project_ids_from_profiles = PartnerProgramUserProfile.objects.values_list(
        "project_id", flat=True
    ).exclude(project_id__isnull=True)

    Project.objects.filter(id__in=project_ids_from_links).update(is_public=False)
    Project.objects.filter(id__in=project_ids_from_profiles).update(is_public=False)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_project_is_public"),
        ("partner_programs", "0015_partnerprogram_publish_projects_after_finish"),
    ]

    operations = [
        migrations.RunPython(hide_program_projects, migrations.RunPython.noop),
    ]
