# Generated by Django 4.2.11 on 2026-05-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_hide_program_projects'),
        ('news', '0007_project_news_2_news_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectNews',
        ),
    ]
