repos:
    - repo: https://github.com/ambv/black
      rev: 22.10.0
      hooks:
          - id: black
            exclude: ^.*\b(migrations)\b.*$
            language_version: python3
    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            additional_dependencies:
            - flake8-print
            - flake8-variables-names
            - flake8-bugbear
            - flake8-builtins
            - flake8-comprehensions
            - flake8-broken-line
            - flake8-mutable