version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    image: app
    restart: always
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0