version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: procollab-dev-api:${IMAGE_TAG:-dev}
    restart: unless-stopped
    volumes:
      - ./log:/procollab/log
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
    ports:
      - "127.0.0.1:8000:8000" 

  redis:
    image: redis:8.6.2
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - redis-data:/data


  celerys:
    container_name: api_celery
    restart: always
    image: procollab-dev-api:${IMAGE_TAG:-dev}
    env_file:
      - .env
    command: bash ./scripts/celery.sh
    depends_on:
      - redis
      #      - db
      - web
    volumes:
      - ./log:/procollab/log
volumes:
  redis-data:
