version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    image: ghcr.io/procollab-github/api:latest
    restart: always
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0