version: '3.9'

services:
  redis:
    image: "redis:alpine"
    command: redis-server 
    expose:
     - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    image: ghcr.io/procollab-github/api:latest
    restart: always
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      REDIS_HOST: redis

volumes:
  redis-data:
  redis-conf: