version: '3.9'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: bash ./scripts/startup.sh
    volumes:
      - ./log:/procollab/log
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
    expose:
      - 8000

  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - web
    ports:
      - "8000:80"

  redis:
    container_name: redis
    image: redis:latest
    expose:
      - 6379
    volumes:
      - redis-data:/data

  celerys:
    container_name: api_celery
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: bash ./scripts/celery.sh
    depends_on:
      - redis
      - web
    volumes:
      - .:/procollab

volumes:
  log:
  redis-data:
