version: '3.9'

services:
  web:
    image: ghcr.io/procollab-github/api:${IMAGE_TAG:?IMAGE_TAG is required}
    restart: unless-stopped
    volumes:
      - ./log:/procollab/log
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
    ports:
      - "127.0.0.1:8000:8000"
  redis:
    image: redis:latest
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - redis-data:/data


  celerys:
    container_name: api_celery
    restart: always
    image: ghcr.io/procollab-github/api:${IMAGE_TAG:?IMAGE_TAG is required}
    env_file:
      - .env
    command: bash ./scripts/celery.sh
    depends_on:
      - redis
#      - db
      - web
    volumes:
      - ./log:/procollab/log

volumes:
  redis-data:
