# Generated by Django 4.2 on 2023-07-03 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import partner_programs.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название")),
                ("tag", models.TextField(verbose_name="Тег")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                ("city", models.TextField(verbose_name="Город")),
                (
                    "image_address",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на аватар"
                    ),
                ),
                (
                    "cover_image_address",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на обложку"
                    ),
                ),
                (
                    "advertisement_image_address",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Ссылка на обложку для рекламы",
                    ),
                ),
                (
                    "presentation_address",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на презентацию"
                    ),
                ),
                (
                    "data_schema",
                    models.JSONField(
                        default=partner_programs.constants.get_default_data_schema,
                        help_text="Ключи - имена полей, значения - тип поля ввода",
                        verbose_name="Схема данных в формате JSON",
                    ),
                ),
                ("datetime_started", models.DateTimeField(verbose_name="Дата начала")),
                (
                    "datetime_finished",
                    models.DateTimeField(verbose_name="Дата окончания"),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
            ],
            options={
                "verbose_name": "Партнерская программа",
                "verbose_name_plural": "Партнерские программы",
            },
        ),
        migrations.CreateModel(
            name="PartnerProgramUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_program_data", models.JSONField()),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "partner_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_program_user_profile",
                        to="partner_programs.partnerprogram",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_program_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя в партнерской программе",
                "verbose_name_plural": "Профили пользователей в партнерских программах",
                "unique_together": {("user", "partner_program")},
            },
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="partner_programs",
                through="partner_programs.PartnerProgramUserProfile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники программы",
            ),
        ),
    ]
