# Generated by Django 4.1.3 on 2023-07-08 18:58
import datetime

import pytz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_programs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partnerprogram",
            options={"verbose_name": "Программа", "verbose_name_plural": "Программы"},
        ),
        migrations.AlterModelOptions(
            name="partnerprogramuserprofile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Профили"},
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="datetime_registration_ends",
            field=models.DateTimeField(
                default=datetime.datetime.now(tz=pytz.utc), verbose_name="Дата окончания регистрации"
            ),
            preserve_default=False,
        ),
    ]
