# Generated by Django 4.2.3 on 2023-07-18 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0019_alter_project_options_project_hidden_score"),
        ("partner_programs", "0002_alter_partnerprogram_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprogramuserprofile",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_program_profiles",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="partnerprogramuserprofile",
            name="partner_program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_program_profiles",
                to="partner_programs.partnerprogram",
            ),
        ),
        migrations.AlterField(
            model_name="partnerprogramuserprofile",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partner_program_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
