# Generated by Django 4.2.3 on 2023-12-29 21:02

from django.db import migrations

from partner_programs.models import PartnerProgramUserProfile

FIELDS_TO_DELETE = [
    'password',
    'formid',
    'tranid',
    'COOKIES',
    'utm_term',
    'utm_medium',
    'utm_source',
    'utm_content',
    'utm_campaign',
]


def normalize_profiles_data(apps, schema_editor):
    for profile in PartnerProgramUserProfile.objects.all():
        program_data = profile.partner_program_data
        if any(field in program_data for field in FIELDS_TO_DELETE):
            program_data['tilda'] = True

        for field in FIELDS_TO_DELETE:
            if field in program_data:
                program_data.pop(field)
        profile.partner_program_data = program_data
        profile.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("partner_programs", "0003_partnerprogramuserprofile_project_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_profiles_data, reverse_code=do_nothing),
    ]
