# Generated by Django 4.2.3 on 2024-04-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_programs", "0004_auto_20231230_0002"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprogram",
            name="draft",
            field=models.BooleanField(default=True),
        ),
    ]
