# Generated by Django 4.2.11 on 2024-07-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_programs", "0005_partnerprogram_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprogram",
            name="projects_availability",
            field=models.CharField(
                choices=[
                    ("all_users", "Всем пользователям"),
                    ("experts_only", "Только экспертам"),
                ],
                default="all_users",
                max_length=25,
                verbose_name="Доступность к дочерним проектам",
            ),
        ),
    ]
