# Generated by Django 4.2.11 on 2025-07-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0007_auto_20230929_1727"),
        ("partner_programs", "0006_partnerprogram_projects_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerProgramMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Например, 'Кейс Сбера'",
                        max_length=255,
                        verbose_name="Название материала",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Укажите ссылку вручную или прикрепите файл",
                        null=True,
                        verbose_name="Ссылка на материал",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        help_text="Если указан файл, ссылка берётся из него",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="files.userfile",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="partner_programs.partnerprogram",
                        verbose_name="Программа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал программы",
                "verbose_name_plural": "Материалы программ",
            },
        ),
    ]
