# Generated by Django 4.2.11 on 2025-07-22 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("partner_programs", "0007_partnerprogrammaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprogram",
            name="managers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Пользователи, имеющие право создавать и редактировать новости",
                related_name="managed_partner_programs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджеры программы",
            ),
        ),
        migrations.AlterField(
            model_name="partnerprogrammaterial",
            name="title",
            field=models.CharField(
                help_text="Укажите текст для гиперссылки",
                max_length=255,
                verbose_name="Название материала",
            ),
        ),
    ]
