# Generated by Django 4.2.11 on 2025-07-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0007_auto_20230929_1727"),
        ("projects", "0027_alter_defaultprojectcover_datetime_created_and_more"),
        ("partner_programs", "0008_partnerprogram_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerProgramField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Служебное имя")),
                (
                    "label",
                    models.CharField(
                        max_length=256, verbose_name="Отображаемое название"
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Однострочный текст"),
                            ("textarea", "Многострочный текст"),
                            ("checkbox", "Чекбокс"),
                            ("select", "Выпадающий список"),
                            ("radio", "Радио-кнопка"),
                            ("file", "Файл"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("help_text", models.TextField(blank=True, null=True)),
                ("show_filter", models.BooleanField(default=False)),
                (
                    "options",
                    models.TextField(
                        blank=True,
                        help_text="Опции через | (для select/radio/checkbox)",
                        null=True,
                    ),
                ),
                (
                    "partner_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="partner_programs.partnerprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительное поле программы",
                "verbose_name_plural": "Дополнительные поля программы",
                "unique_together": {("partner_program", "name")},
            },
        ),
        migrations.CreateModel(
            name="PartnerProgramProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_updated", models.DateTimeField(auto_now=True)),
                (
                    "partner_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_projects",
                        to="partner_programs.partnerprogram",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_links",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участие проекта в программе",
                "verbose_name_plural": "Участия проекта в программах",
                "unique_together": {("partner_program", "project")},
            },
        ),
        migrations.CreateModel(
            name="PartnerProgramFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="partner_programs.partnerprogramfield",
                    ),
                ),
                (
                    "program_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_values",
                        to="partner_programs.partnerprogramproject",
                    ),
                ),
                (
                    "value_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_field_usages",
                        to="files.userfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значение поля программы для проекта",
                "verbose_name_plural": "Значения полей программы для проекта",
                "unique_together": {("program_project", "field")},
            },
        ),
    ]
