# Generated by Django 4.2.11 on 2025-07-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_programs", "0009_partnerprogramfield_partnerprogramproject_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partnerprogramfield",
            options={
                "verbose_name": "Дополнительное поле программы",
                "verbose_name_plural": "Дополнительные поля программ",
            },
        ),
        migrations.AlterModelOptions(
            name="partnerprogramproject",
            options={
                "verbose_name": "Проект участующий в программе",
                "verbose_name_plural": "Проекеты участвующие в программах",
            },
        ),
        migrations.RemoveField(
            model_name="partnerprogramfieldvalue",
            name="value_file",
        ),
        migrations.AlterField(
            model_name="partnerprogramfieldvalue",
            name="value_text",
            field=models.TextField(default="Нет значения"),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="partnerprogramfieldvalue",
            index=models.Index(
                fields=["program_project"], name="partner_pro_program_8cb59d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnerprogramfieldvalue",
            index=models.Index(fields=["field"], name="partner_pro_field_i_6a74d2_idx"),
        ),
    ]
