# Generated by Django 4.2.11 on 2025-08-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_programs", "0010_alter_partnerprogramfield_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprogram",
            name="is_competitive",
            field=models.BooleanField(
                default=False,
                help_text="Если включено, проекты участников подлежат сдаче на проверку",
                verbose_name="Конкурсная программа",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogramproject",
            name="datetime_submitted",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата сдачи проекта"
            ),
        ),
        migrations.AddField(
            model_name="partnerprogramproject",
            name="submitted",
            field=models.BooleanField(default=False, verbose_name="Проект сдан"),
        ),
    ]
