# Generated by Django 4.2.24 on 2025-10-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_programs', '0011_partnerprogram_is_competitive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprogram',
            name='registration_link',
            field=models.URLField(blank=True, help_text='Адрес страницы регистрации (например, на Tilda)', null=True, verbose_name='Ссылка на регистрацию'),
        ),
    ]
