# Generated by Django 4.2.11 on 2025-12-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_programs", "0012_partnerprogram_registration_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprogram",
            name="max_project_rates",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                help_text="Ограничение на число экспертов, которые могут оценить один проект в программе",
                null=True,
                verbose_name="Максимальное количество оценок проектов",
            ),
        ),
    ]
