# Generated by Codex CLI on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_programs", "0014_partnerprogram_datetime_evaluation_ends_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprogram",
            name="publish_projects_after_finish",
            field=models.BooleanField(
                default=False,
                help_text="Если включено, проекты участников могут стать публичными после завершения программы",
                verbose_name="Публиковать проекты после окончания программы",
            ),
        ),
    ]

