# Generated by Django 4.2.11 on 2026-06-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partner_programs", "0016_partnerprogram_is_distributed_evaluation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partnerprogramproject",
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
    ]
