# Generated by Django 4.2.11 on 2026-09-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner_programs", "0018_partnerprogramuserprofile_welcome_acknowledged_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprogram",
            name="legacy_team_max_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="NULL — без максимума. Ожидающие приглашения резервируют места.",
                null=True,
                verbose_name="Максимум участников legacy-команды",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="legacy_team_min_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="NULL — без минимума. Проверяется только при сдаче проекта.",
                null=True,
                verbose_name="Минимум участников legacy-команды",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerprogram",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("legacy_team_min_size__isnull", True),
                    ("legacy_team_min_size__gte", 1),
                    _connector="OR",
                ),
                name="legacy_team_min_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerprogram",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("legacy_team_max_size__isnull", True),
                    ("legacy_team_max_size__gte", 1),
                    _connector="OR",
                ),
                name="legacy_team_max_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerprogram",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("legacy_team_min_size__isnull", True),
                    ("legacy_team_max_size__isnull", True),
                    ("legacy_team_max_size__gte", models.F("legacy_team_min_size")),
                    _connector="OR",
                ),
                name="legacy_team_max_gte_min",
            ),
        ),
    ]
