# Generated by Django 4.2.11 on 2026-07-21 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("partner_programs", "0019_submission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Команда заявки",
                "verbose_name_plural": "Команды заявок",
            },
        ),
        migrations.AddField(
            model_name="application",
            name="participation_mode",
            field=models.CharField(
                choices=[
                    ("undecided", "Не определен"),
                    ("individual", "Индивидуально"),
                    ("team", "В команде"),
                ],
                default="individual",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("captain", "Капитан"), ("member", "Участник")],
                        default="member",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Приглашен"),
                            ("accepted", "Принят"),
                            ("declined", "Отклонил приглашение"),
                            ("removed", "Исключен"),
                            ("left", "Покинул команду"),
                        ],
                        default="invited",
                        max_length=16,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited_application_team_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="partner_programs.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_team_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник команды заявки",
                "verbose_name_plural": "Участники команд заявок",
            },
        ),
        migrations.AddField(
            model_name="team",
            name="application",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="partner_programs.application",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="captain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="captained_application_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                fields=("team", "user"), name="uniq_team_member_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "captain"), ("status", "accepted")),
                fields=("team",),
                name="uniq_accepted_captain_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("role", "captain"), _negated=True),
                    ("status", "accepted"),
                    _connector="OR",
                ),
                name="captain_team_member_is_accepted",
            ),
        ),
    ]
