# Generated by Django 4.2.11 on 2026-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "partner_programs",
            "0020_team_application_participation_mode_teammember_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprogram",
            name="datetime_application_ends",
            field=models.DateTimeField(
                blank=True,
                help_text="Отдельный дедлайн Application; другие дедлайны не используются как fallback",
                null=True,
                verbose_name="Дата окончания подачи заявок",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="participation_format",
            field=models.CharField(
                choices=[
                    ("individual_only", "Только индивидуально"),
                    ("team_only", "Только в команде"),
                    ("individual_or_team", "Индивидуально или в команде"),
                ],
                default="individual_only",
                max_length=24,
                verbose_name="Разрешенный формат участия",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="team_max_size",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Количество принятых участников с учетом капитана",
                null=True,
                verbose_name="Максимальный размер команды",
            ),
        ),
        migrations.AddField(
            model_name="partnerprogram",
            name="team_min_size",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Количество принятых участников с учетом капитана",
                null=True,
                verbose_name="Минимальный размер команды",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerprogram",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("team_min_size__isnull", True),
                    ("team_min_size__gte", 2),
                    _connector="OR",
                ),
                name="program_team_min_gte_2_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerprogram",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("team_max_size__isnull", True),
                    ("team_max_size__gte", 2),
                    _connector="OR",
                ),
                name="program_team_max_gte_2_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerprogram",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("team_min_size__isnull", True),
                    ("team_max_size__isnull", True),
                    ("team_max_size__gte", models.F("team_min_size")),
                    _connector="OR",
                ),
                name="program_team_max_gte_min",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerprogram",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("participation_format", "individual_only"),
                        ("team_max_size__isnull", True),
                        ("team_min_size__isnull", True),
                    ),
                    models.Q(
                        ("participation_format__in", ("team_only", "individual_or_team")),
                        ("team_max_size__isnull", False),
                        ("team_min_size__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="program_team_sizes_match_format",
            ),
        ),
    ]
