# Generated by Django 4.2.11 on 2026-07-22 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner_programs', '0021_partnerprogram_datetime_application_ends_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('revoked', 'Отозвано')], default='pending', max_length=16, verbose_name='Статус')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_application_team_invites', to=settings.AUTH_USER_MODEL, verbose_name='Кем приглашен')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='partner_programs.team', verbose_name='Команда')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_team_invites', to=settings.AUTH_USER_MODEL, verbose_name='Приглашенный пользователь')),
            ],
            options={
                'verbose_name': 'Приглашение в команду заявки',
                'verbose_name_plural': 'Приглашения в команды заявок',
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='team_invite_user_status_idx'), models.Index(fields=['team', 'status', 'created_at'], name='team_invite_team_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='teaminvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('team', 'user'), name='uniq_pending_invite_team_user'),
        ),
    ]
