# Generated by Django 4.1.2 on 2022-10-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="short_text",
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
