# Generated by Django 4.1.2 on 2022-10-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_short_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="cover_url",
            field=models.URLField(),
        ),
    ]
