# Generated by Django 4.1.2 on 2022-10-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_news_tags_alter_newstag_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="news.newstag", verbose_name="Список тегов"
            ),
        ),
    ]
