# Generated by Django 4.2.3 on 2023-07-12 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("news", "0004_alter_news_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
