# Generated by Django 4.2.3 on 2023-07-12 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("news", "0005_news_content_type_news_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="contenttypes.contenttype",
            ),
        ),
    ]
