# Generated by Django 4.2.3 on 2023-07-20 18:34

from django.db import migrations
from django.db.migrations import RunPython


def project_news_to_news_news(apps, schema_editor):
    # add ProjectNews model to news app via schema_editor
    ProjectNews = apps.get_model("projects.ProjectNews")
    News = apps.get_model("news", "News")
    ContentType = apps.get_model("contenttypes", "ContentType")
    for project_news in ProjectNews.objects.all():
        project_content_type = ContentType.objects.get(
            app_label="projects", model="project"
        )
        News.objects.create(
            text=project_news.text,
            content_type=project_content_type,
            object_id=project_news.project.id,
            files=project_news.files.all(),
            views=project_news.views.all(),
            likes=project_news.likes.all(),
            datetime_created=project_news.datetime_created,
            datetime_updated=project_news.datetime_updated
        )


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_news_options_remove_news_cover_url_and_more"),
        ("projects", "0013_projectnews")
    ]

    operations = [
        RunPython(project_news_to_news_news)
    ]
