# Generated by Django 4.2.3 on 2023-07-20 18:34
import os

from django.db import migrations
from django.db.migrations import RunPython


def project_news_to_news_news(apps, schema_editor):
    ProjectNews = apps.get_model("projects.ProjectNews")
    News = apps.get_model("news", "News")
    ContentType = apps.get_model("contenttypes", "ContentType")
    content_type_count = ContentType.objects.all().count()
    if content_type_count == 0:
        return

    project_news_content_type = ContentType.objects.get(
        app_label="projects", model="projectnews"
    )
    project_content_type = ContentType.objects.get(
        app_label="projects", model="project"
    )

    news_content_type = ContentType.objects.get(app_label="news", model="news")
    Like = apps.get_model("core", "Like")
    View = apps.get_model("core", "View")
    for project_news in ProjectNews.objects.all():
        obj = News.objects.create(
            text=project_news.text,
            content_type=project_content_type,
            object_id=project_news.project.id,
            datetime_created=project_news.datetime_created,
            datetime_updated=project_news.datetime_updated
        )
        obj.files.set(project_news.files.all())
        likes = Like.objects.filter(
            content_type=project_news_content_type,
            object_id=project_news.id,
        )
        views = View.objects.filter(
            content_type=project_news_content_type,
            object_id=project_news.id,
        )
        for i in likes:
            i.content_type = news_content_type
            i.object_id = obj.id
            i.save()
        for i in views:
            i.content_type = news_content_type
            i.object_id = obj.id
            i.save()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0006_alter_news_options_remove_news_cover_url_and_more"),
        ("projects", "0013_projectnews"),
        ("projects", "0001_initial"),
        ("projects", "0002_initial"),
    ]

    operations = [
        RunPython(project_news_to_news_news, reverse_code=migrations.RunPython.noop)
    ]
