# Generated by Django 4.2.3 on 2024-02-23 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_project_news_2_news_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="datetime_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
    ]
