# Generated by Django 4.2.11 on 2024-08-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_alter_news_datetime_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="pin",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Закрепить новость (пока только для профиля программ)",
                verbose_name="Закрепить новость",
            ),
        ),
    ]
