# Generated by Django 4.2.3 on 2023-07-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0003_link"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="link",
            unique_together={("link", "content_type", "object_id")},
        ),
    ]
