# Generated by Django 4.2.3 on 2024-01-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0008_auto_20231223_1331"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name": "Категория навыка",
                "verbose_name_plural": "Категории навыков",
                "ordering": ["category"],
            },
        ),
        migrations.CreateModel(
            name="SpecializationToObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "specialization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specializations",
                        to="core.specialization",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["category", "skill"],
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
            },
        ),
        migrations.DeleteModel(
            name="UserSkillTag",
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="core.skillcategory",
            ),
            preserve_default=False,
        ),
    ]
