# Generated by Django 4.2.3 on 2024-01-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20240128_2214"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="specialization",
            options={
                "verbose_name": "Специализация",
                "verbose_name_plural": "Специализации",
            },
        ),
        migrations.AlterModelOptions(
            name="specializationcategory",
            options={
                "verbose_name": "Категория специализации",
                "verbose_name_plural": "Категории специализаций",
            },
        ),
    ]
