# Generated by Django 4.2.11 on 2024-07-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_migrate_key_skills_to_skills"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["id", "category", "name"],
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
            },
        ),
        migrations.AlterModelOptions(
            name="skilltoobject",
            options={
                "verbose_name": "Ссылка на навык",
                "verbose_name_plural": "Ссылки на навыки",
            },
        ),
    ]
