# Generated by Django 4.2.24 on 2025-11-20 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0030_company_resource_projectcompany_project_companies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('purple', 'Purple'), ('red', 'Red')], default='blue', max_length=32)),
                ('icon', models.CharField(choices=[('rocket', 'Rocket'), ('target', 'Target'), ('bulb', 'Light Bulb'), ('chart', 'Chart'), ('note', 'Note')], default='rocket', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_boards', to='projects.project')),
            ],
            options={
                'verbose_name': 'Kanban board',
                'verbose_name_plural': 'Kanban boards',
                'ordering': ['project_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tasks_count', models.PositiveIntegerField(default=0, editable=False, help_text='Cached value of tasks inside the column.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='kanban.board')),
            ],
            options={
                'verbose_name': 'Board column',
                'verbose_name_plural': 'Board columns',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='boardcolumn',
            constraint=models.UniqueConstraint(fields=('board', 'order'), name='unique_column_order_per_board'),
        ),
        migrations.AddConstraint(
            model_name='boardcolumn',
            constraint=models.UniqueConstraint(fields=('board', 'name'), name='unique_column_name_per_board'),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('project', 'name')},
        ),
    ]
