# Generated by Django 4.1.2 on 2022-10-14 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('photo_address', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('key_skills', models.CharField(max_length=255)),
                ('useful_to_project', models.CharField(max_length=255)),
                ('about_me', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('achievements', models.JSONField()),
                ('tags', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
