global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: monitoring
    metrics_path: /django_prometheus/metrics
    static_configs:
      - targets:
        - web:8000