global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - alerts.yml


alerting:
     alertmanagers:
     - static_configs:
       - targets:
         - 'alertmanager:9093'


scrape_configs:
  - job_name: monitoring
    metrics_path: /django_prometheus/metrics
    static_configs:
      - targets:
        - web:8000

