# Generated by Django 4.1.2 on 2022-10-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancyrequest",
            name="is_approve",
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
