# Generated by Django 4.2.3 on 2024-03-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacancy",
            old_name="required_skills",
            new_name="required_skills_old",
        ),
    ]
