# Generated by Django 4.2.3 on 2024-03-02 22:32
from django.contrib.contenttypes.models import ContentType
from django.db import migrations
from core.models import Skill, SkillToObject
from vacancy.models import Vacancy

vacancy_content_type = ContentType.objects.get_for_model(Vacancy)


def migrate_required_skills(apps, schema_editor):
    for vacancy in Vacancy.objects.all():
        if vacancy.required_skills_old:
            for skill_name in vacancy.required_skills_old.lower().split(','):
                skill_name = skill_name.strip()
                skill = Skill.objects.filter(name__iexact=skill_name).first()
                if skill:
                    SkillToObject.objects.get_or_create(
                        skill=skill, content_type=vacancy_content_type, object_id=vacancy.id
                    )


def reverse(apps, schema_editor):
    SkillToObject.objects.filter(content_type=vacancy_content_type).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("vacancy", "0002_rename_required_skills_vacancy_required_skills_old"),
        ("core", "0013_add_skills_from_dataset")
    ]

    operations = [
        migrations.RunPython(migrate_required_skills, reverse_code=reverse),
    ]
