# Generated by Django 4.1.2 on 2022-10-23 19:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vacancy", "0003_alter_vacancyrequest_is_approve"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VacancyRequest",
            new_name="VacancyResponse",
        ),
        migrations.AlterModelOptions(
            name="vacancyresponse",
            options={
                "ordering": ["-datetime_created"],
                "verbose_name": "Отклик на вакансию",
                "verbose_name_plural": "Отклик на вакансии",
            },
        ),
        migrations.RenameField(
            model_name="vacancyresponse",
            old_name="is_approve",
            new_name="is_approved",
        ),
    ]
