# Generated by Django 4.2.11 on 2024-07-01 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0007_auto_20230929_1727"),
        ("vacancy", "0003_migrate_old_required_skills_to_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancyresponse",
            name="accompanying_file",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vacancy_file",
                to="files.userfile",
                verbose_name="Сопроводительный файл",
            ),
        ),
    ]
