# Generated by Django 4.2.11 on 2024-07-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0004_vacancyresponse_accompanying_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="required_skills_old",
        ),
    ]
