# Generated by Django 4.1.2 on 2022-10-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0004_rename_vacancyrequest_vacancyresponse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancyresponse",
            name="why_me",
            field=models.TextField(blank=True),
        ),
    ]
