# Generated by Django 4.2.11 on 2024-07-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0005_remove_vacancy_required_skills_old"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="datetime_closed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата закрытия"
            ),
        ),
    ]
