# Generated by Django 4.2.11 on 2024-12-04 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0007_vacancy_required_experience_vacancy_work_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="salary",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Зарплата",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="required_experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_experience", "без опыта"),
                    ("up_to_a_year", "до 1 года"),
                    ("from_one_to_three_years", "от 1 года до 3 лет"),
                    ("from_three_years", "от 3 лет и более"),
                ],
                max_length=50,
                null=True,
                verbose_name="Требуемый опыт",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="work_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("remote", "удаленная работа"),
                    ("office", "работа в офисе"),
                    ("hybrid", "смешанный формат"),
                ],
                max_length=50,
                null=True,
                verbose_name="Формат работы",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="work_schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "полный рабочий день"),
                    ("shift_work", "сменный график"),
                    ("flexible_schedule", "гибкий график"),
                    ("part_time", "частичная занятость"),
                    ("internship", "стажировка"),
                ],
                max_length=50,
                null=True,
                verbose_name="График работы",
            ),
        ),
    ]
