# Generated by Django 4.2.11 on 2025-07-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0008_vacancy_salary_alter_vacancy_required_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="specialization",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Специализация"
            ),
        ),
    ]
