# Generated by Django 4.2.11 on 2026-08-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy", "0009_vacancy_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Город"
            ),
        ),
    ]
