# Generated by Django 4.2.3 on 2024-02-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rate_projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectscore",
            name="comment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="projectscore",
            name="value_float",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Значение с плавающей запятой"
            ),
        ),
        migrations.AlterField(
            model_name="projectscore",
            name="value_str",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Текстовое значение"
            ),
        ),
    ]
