# Generated by Django 4.2.11 on 2026-02-20 05:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner_programs', '0016_partnerprogram_is_distributed_evaluation'),
        ('files', '0007_auto_20230929_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(600)], verbose_name='Описание')),
                ('access_type', models.CharField(choices=[('all_users', 'Для всех пользователей'), ('program_members', 'Для участников программы'), ('subscription_stub', 'По подписке')], default='all_users', max_length=32, verbose_name='Тип доступа')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата старта')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('completed', 'Завершен')], default='draft', max_length=16, verbose_name='Статус курса')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Курс завершен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('avatar_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_avatars', to='files.userfile', verbose_name='Аватар курса')),
                ('card_cover_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_card_covers', to='files.userfile', verbose_name='Обложка карточки курса')),
                ('header_cover_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_header_covers', to='files.userfile', verbose_name='Обложка шапки курса')),
                ('partner_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='partner_programs.partnerprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('-datetime_created',),
            },
        ),
    ]
