# Generated by Django 4.2.11 on 2026-02-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('access_type', 'program_members'), _negated=True), ('partner_program__isnull', False), _connector='OR'), name='courses_program_members_requires_program'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('end_date__isnull', True), ('start_date__isnull', True)), models.Q(('end_date__isnull', False), ('start_date__isnull', False)), _connector='OR'), name='courses_dates_must_be_set_together'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='courses_end_date_gte_start_date'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'completed'), _negated=True), ('is_completed', True), _connector='OR'), name='courses_completed_status_implies_flag'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('is_completed', False), ('status', 'completed'), _connector='OR'), name='courses_completed_flag_implies_status'),
        ),
    ]
