# Generated by Django 4.2.11 on 2026-02-20 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20230929_1727'),
        ('courses', '0002_course_courses_program_members_requires_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название модуля')),
                ('start_date', models.DateField(verbose_name='Дата старта модуля')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=16, verbose_name='Статус модуля')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядковый номер')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('avatar_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_module_avatars', to='files.userfile', verbose_name='Аватар модуля')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль курса',
                'verbose_name_plural': 'Модули курса',
                'ordering': ('course_id', 'order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='courses_module_unique_course_order'),
        ),
        migrations.AddConstraint(
            model_name='coursemodule',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 1)), name='courses_module_order_gte_1'),
        ),
    ]
