# Generated by Django 4.2.11 on 2026-02-20 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursemodule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Название урока')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=16, verbose_name='Статус урока')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядковый номер')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.coursemodule', verbose_name='Модуль курса')),
            ],
            options={
                'verbose_name': 'Урок курса',
                'verbose_name_plural': 'Уроки курса',
                'ordering': ('module_id', 'order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='courselesson',
            constraint=models.UniqueConstraint(fields=('module', 'order'), name='courses_lesson_unique_module_order'),
        ),
        migrations.AddConstraint(
            model_name='courselesson',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 1)), name='courses_lesson_order_gte_1'),
        ),
    ]
