# Generated by Django 4.2.11 on 2026-02-20 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0007_auto_20230929_1727'),
        ('courses', '0004_courselesson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('body_text', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', max_length=16, verbose_name='Статус задания')),
                ('task_kind', models.CharField(choices=[('informational', 'Информационное'), ('question', 'Вопрос/ответ')], max_length=16, verbose_name='Тип задания')),
                ('check_type', models.CharField(blank=True, choices=[('without_review', 'Без проверки'), ('with_review', 'С проверкой')], max_length=16, null=True, verbose_name='Тип проверки')),
                ('informational_type', models.CharField(blank=True, choices=[('video_text', 'Видео и текст'), ('text', 'Текст'), ('text_image', 'Текст и изображение')], max_length=24, null=True, verbose_name='Тип информационного задания')),
                ('question_type', models.CharField(blank=True, choices=[('image_text', 'Изображение и текст'), ('video', 'Видео'), ('image', 'Изображение'), ('text_file', 'Текст с файлом'), ('text', 'Текст')], max_length=24, null=True, verbose_name='Тип вопроса')),
                ('answer_type', models.CharField(blank=True, choices=[('text', 'Текст'), ('text_and_files', 'Текст и загрузка файла'), ('files', 'Загрузка файла'), ('multiple_choice', 'Выбор одного или нескольких вариантов ответа'), ('single_choice', 'Выбор одного варианта ответа')], max_length=24, null=True, verbose_name='Тип ответа')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядковый номер')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('attachment_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_task_attachments', to='files.userfile', verbose_name='Файл')),
                ('image_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_task_images', to='files.userfile', verbose_name='Изображение')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.courselesson', verbose_name='Урок курса')),
            ],
            options={
                'verbose_name': 'Задание курса',
                'verbose_name_plural': 'Задания курса',
                'ordering': ('lesson_id', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CourseTaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный вариант')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядковый номер')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.coursetask', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Вариант ответа задания',
                'verbose_name_plural': 'Варианты ответов задания',
                'ordering': ('task_id', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UserTaskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Отправлено'), ('pending_review', 'Ожидает проверки'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='submitted', max_length=20, verbose_name='Статус ответа')),
                ('answer_text', models.CharField(blank=True, default='', max_length=1000, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Ответ корректен')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время отправки')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='Комментарий проверяющего')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время проверки')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_course_task_answers', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='courses.coursetask', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_task_answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ пользователя на задание',
                'verbose_name_plural': 'Ответы пользователей на задания',
                'ordering': ('-submitted_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UserTaskAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='courses.usertaskanswer', verbose_name='Ответ пользователя')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_in_answers', to='courses.coursetaskoption', verbose_name='Выбранный вариант')),
            ],
            options={
                'verbose_name': 'Выбранный вариант ответа',
                'verbose_name_plural': 'Выбранные варианты ответа',
            },
        ),
        migrations.CreateModel(
            name='UserTaskAnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(blank=True, default='', verbose_name='Название файла')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='Размер файла')),
                ('datetime_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.usertaskanswer', verbose_name='Ответ пользователя')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_task_answer_files', to='files.userfile', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл ответа пользователя',
                'verbose_name_plural': 'Файлы ответов пользователей',
                'ordering': ('-datetime_uploaded', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='usertaskansweroption',
            constraint=models.UniqueConstraint(fields=('answer', 'option'), name='courses_user_task_answer_option_unique_answer_option'),
        ),
        migrations.AddConstraint(
            model_name='usertaskanswerfile',
            constraint=models.UniqueConstraint(fields=('answer', 'file'), name='courses_user_task_answer_file_unique_answer_file'),
        ),
        migrations.AddConstraint(
            model_name='usertaskanswer',
            constraint=models.UniqueConstraint(fields=('user', 'task'), name='courses_user_task_answer_unique_user_task'),
        ),
        migrations.AddConstraint(
            model_name='coursetaskoption',
            constraint=models.UniqueConstraint(fields=('task', 'order'), name='courses_task_option_unique_task_order'),
        ),
        migrations.AddConstraint(
            model_name='coursetaskoption',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 1)), name='courses_task_option_order_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='coursetask',
            constraint=models.UniqueConstraint(fields=('lesson', 'order'), name='courses_task_unique_lesson_order'),
        ),
        migrations.AddConstraint(
            model_name='coursetask',
            constraint=models.CheckConstraint(check=models.Q(('order__gte', 1)), name='courses_task_order_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='coursetask',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('task_kind', 'informational'), _negated=True), ('informational_type__isnull', False), _connector='OR'), name='courses_task_info_requires_info_type'),
        ),
        migrations.AddConstraint(
            model_name='coursetask',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('task_kind', 'question'), _negated=True), models.Q(('question_type__isnull', False), ('answer_type__isnull', False), ('check_type__isnull', False)), _connector='OR'), name='courses_task_question_requires_types'),
        ),
        migrations.AddConstraint(
            model_name='coursetask',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('task_kind', 'informational'), _negated=True), models.Q(('question_type__isnull', True), ('answer_type__isnull', True), ('check_type__isnull', True)), _connector='OR'), name='courses_task_info_forbids_question_fields'),
        ),
        migrations.AddConstraint(
            model_name='coursetask',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('task_kind', 'question'), _negated=True), ('informational_type__isnull', True), _connector='OR'), name='courses_task_question_forbids_info_type'),
        ),
    ]
