# Generated by Django 4.2.11 on 2026-03-03 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0005_coursetask_coursetaskoption_usertaskanswer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Не начато"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершено"),
                            ("blocked", "Заблокировано"),
                        ],
                        default="not_started",
                        max_length=16,
                        verbose_name="Статус прогресса",
                    ),
                ),
                (
                    "percent",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Прогресс, %"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "last_visit_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата последнего визита"
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progresses",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_progresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс пользователя по курсу",
                "verbose_name_plural": "Прогресс пользователей по курсам",
                "ordering": ("-datetime_updated", "id"),
            },
        ),
        migrations.CreateModel(
            name="UserLessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Не начато"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершено"),
                            ("blocked", "Заблокировано"),
                        ],
                        default="not_started",
                        max_length=16,
                        verbose_name="Статус прогресса",
                    ),
                ),
                (
                    "percent",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Прогресс, %"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "current_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_in_lesson_progress",
                        to="courses.coursetask",
                        verbose_name="Текущее задание",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progresses",
                        to="courses.courselesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс пользователя по уроку",
                "verbose_name_plural": "Прогресс пользователей по урокам",
                "ordering": ("-datetime_updated", "id"),
            },
        ),
        migrations.CreateModel(
            name="UserModuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Не начато"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершено"),
                            ("blocked", "Заблокировано"),
                        ],
                        default="not_started",
                        max_length=16,
                        verbose_name="Статус прогресса",
                    ),
                ),
                (
                    "percent",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Прогресс, %"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "datetime_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progresses",
                        to="courses.coursemodule",
                        verbose_name="Модуль",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_progresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс пользователя по модулю",
                "verbose_name_plural": "Прогресс пользователей по модулям",
                "ordering": ("-datetime_updated", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="usercourseprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "course"),
                name="courses_user_course_progress_unique_user_course",
            ),
        ),
        migrations.AddConstraint(
            model_name="usercourseprogress",
            constraint=models.CheckConstraint(
                check=models.Q(("percent__gte", 0), ("percent__lte", 100)),
                name="courses_user_course_progress_percent_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="usercourseprogress",
            constraint=models.CheckConstraint(
                check=models.Q(("status", "blocked"), _negated=True),
                name="courses_user_course_progress_status_no_blocked",
            ),
        ),
        migrations.AddConstraint(
            model_name="usercourseprogress",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("percent", 0), ("status", "not_started")),
                    models.Q(
                        ("percent__gte", 1),
                        ("percent__lte", 99),
                        ("status", "in_progress"),
                    ),
                    models.Q(("percent", 100), ("status", "completed")),
                    _connector="OR",
                ),
                name="courses_user_course_progress_status_percent_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="userlessonprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "lesson"),
                name="courses_user_lesson_progress_unique_user_lesson",
            ),
        ),
        migrations.AddConstraint(
            model_name="userlessonprogress",
            constraint=models.CheckConstraint(
                check=models.Q(("percent__gte", 0), ("percent__lte", 100)),
                name="courses_user_lesson_progress_percent_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="userlessonprogress",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("percent", 0), ("status", "not_started")),
                    models.Q(
                        ("percent__gte", 1),
                        ("percent__lte", 99),
                        ("status", "in_progress"),
                    ),
                    models.Q(("percent", 100), ("status", "completed")),
                    models.Q(("percent", 0), ("status", "blocked")),
                    _connector="OR",
                ),
                name="courses_user_lesson_progress_status_percent_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="usermoduleprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "module"),
                name="courses_user_module_progress_unique_user_module",
            ),
        ),
        migrations.AddConstraint(
            model_name="usermoduleprogress",
            constraint=models.CheckConstraint(
                check=models.Q(("percent__gte", 0), ("percent__lte", 100)),
                name="courses_user_module_progress_percent_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="usermoduleprogress",
            constraint=models.CheckConstraint(
                check=models.Q(("status", "blocked"), _negated=True),
                name="courses_user_module_progress_status_no_blocked",
            ),
        ),
        migrations.AddConstraint(
            model_name="usermoduleprogress",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("percent", 0), ("status", "not_started")),
                    models.Q(
                        ("percent__gte", 1),
                        ("percent__lte", 99),
                        ("status", "in_progress"),
                    ),
                    models.Q(("percent", 100), ("status", "completed")),
                    _connector="OR",
                ),
                name="courses_user_module_progress_status_percent_valid",
            ),
        ),
    ]
