# Generated by Django 4.2.11 on 2026-03-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_usercourseprogress_userlessonprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='answer_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок блока ответа'),
        ),
    ]
