# Generated by Django 4.1.3 on 2023-01-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="directchatmessage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectchatmessage",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
