# Generated by Django 4.1.3 on 2023-01-21 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0010_alter_collaborator_user"),
        ("chats", "0002_alter_message_options_chat_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=8192)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="chats.basemessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectChat",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="direct_chats", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Личный чат",
                "verbose_name_plural": "Личные чаты",
            },
        ),
        migrations.CreateModel(
            name="ProjectChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_chats",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чат проекта",
                "verbose_name_plural": "Чаты проектов",
            },
        ),
        migrations.RemoveField(
            model_name="message",
            name="author",
        ),
        migrations.RemoveField(
            model_name="message",
            name="chat",
        ),
        migrations.CreateModel(
            name="DirectChatMessage",
            fields=[
                (
                    "basemessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chats.basemessage",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.directchat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение в личном чате",
                "verbose_name_plural": "Сообщения в личных чатах",
            },
            bases=("chats.basemessage",),
        ),
        migrations.CreateModel(
            name="ProjectChatMessage",
            fields=[
                (
                    "basemessage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="chats.basemessage",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chats.projectchat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение в чате проекта",
                "verbose_name_plural": "Сообщения в чатах проектов",
            },
            bases=("chats.basemessage",),
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
