# Generated by Django 4.1.3 on 2023-03-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_reply_to_constaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="directchatmessage",
            name="file_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectchatmessage",
            name="file_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
