# Generated by Django 4.1.3 on 2023-01-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_basemessage_directchat_projectchat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectchat",
            name="id",
            field=models.PositiveIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
