# Generated by Django 4.1.3 on 2023-03-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_reply_to_constaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="directchatmessage",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectchatmessage",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
    ]
