# Generated by Django 4.1.3 on 2023-03-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_remove_userfile_id_alter_userfile_link"),
        ("chats", "0004_directchatmessage_file_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatAttachment",
            fields=[
                (
                    "userfile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="files.userfile",
                    ),
                ),
            ],
            bases=("files.userfile",),
        ),
    ]
