# Generated by Django 4.1.3 on 2023-03-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_directchatmessage_is_edited_and_more"),
        ("chats", "0005_chatattachment"),
    ]

    operations = []
