# Generated by Django 4.1.3 on 2023-03-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_merge_20230323_0027"),
    ]

    operations = [

        migrations.DeleteModel(
            name="ChatAttachment",
        ),
    ]
