# Generated by Django 4.1.3 on 2023-04-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0006_merge_20230323_0027"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="directchatmessage",
            name="file_url",
        ),
        migrations.RemoveField(
            model_name="projectchatmessage",
            name="file_url",
        ),
        migrations.DeleteModel(
            name="ChatAttachment",
        ),
    ]
