# Generated by Django 4.1.3 on 2023-03-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_userfile_extension_userfile_name_userfile_size"),
        ("chats", "0009_filetomessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filetomessage",
            name="file",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="file_to_message",
                serialize=False,
                to="files.userfile",
            ),
        ),
    ]
