# Generated by Django 4.1.2 on 2022-11-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userfile",
            name="id",
        ),
        migrations.AlterField(
            model_name="userfile",
            name="link",
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
