# Generated by Django 4.1.3 on 2023-03-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_remove_userfile_id_alter_userfile_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="extension",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userfile",
            name="name",
            field=models.TextField(default="file"),
        ),
        migrations.AddField(
            model_name="userfile",
            name="size",
            field=models.PositiveBigIntegerField(blank=True, default=1),
        ),
    ]
