# Generated by Django 4.1.3 on 2023-03-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_remove_userfile_id_alter_userfile_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="extension",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="userfile",
            name="name",
            field=models.CharField(default="file", max_length=512),
        ),
        migrations.AddField(
            model_name="userfile",
            name="size",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
