# Generated by Django 4.1.3 on 2023-07-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_userfile_extension_userfile_name_userfile_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfile",
            name="mime_type",
            field=models.CharField(default="", max_length=256),
        ),
    ]
