# Generated by Django 4.1.3 on 2023-03-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_userfile_extension_userfile_name_userfile_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="extension",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="userfile",
            name="name",
            field=models.TextField(default="file"),
        ),
        migrations.AlterField(
            model_name="userfile",
            name="size",
            field=models.PositiveBigIntegerField(blank=True, default=1),
        ),
    ]
