# Generated by Django 4.1.3 on 2023-07-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_userfile_mime_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userfile",
            options={"verbose_name": "Файл", "verbose_name_plural": "Файлы"},
        ),
    ]
