# Generated by Django 4.2.3 on 2023-09-29 14:27

from io import BytesIO
from django.db import migrations
import requests
import webp

from PIL import Image

from files.service import SelectelSwiftStorage


def convert_image_to_webp(pil_image: Image, quality: int) -> bytes:
    config = webp.WebPConfig.new(preset=webp.WebPPreset.PHOTO, quality=quality)
    webp_image = webp.WebPPicture.from_pil(pil_image)
    return webp_image.encode(config)


def migration(apps, schema_editor):
    UserFile = apps.get_model("files", "UserFile")
    files = UserFile.objects.all()
    storage = SelectelSwiftStorage()
    for i in files:
        # get all files that end in a .png or .jpg
        if i.link.endswith(".png") or i.link.endswith(".jpg"):
            # convert .png/.jpg to .webp
            # download file and convert it to PIL image
            file = requests.get(i.link)
            pil_image = Image.open(BytesIO(file.content))
            webp_file = convert_image_to_webp(pil_image, quality=80)
            storage.delete(i.link)
            storage.upload()
            token = storage._get_auth_token()

            link_with_webp = i.link.split(".")[0] + ".webp"

            requests.put(
                link_with_webp,
                headers={
                    "X-Auth-Token": token,
                    "Content-Type": file.content_type,
                },
                data=file.buffer,
            )
            i.link = link_with_webp
            i.save()


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0005_alter_userfile_options"),
    ]

    operations = []
