# Generated by Django 4.2.11 on 2026-02-12 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_alter_userachievement_year'),
        ('partner_programs', '0016_partnerprogram_is_distributed_evaluation'),
        ('projects', '0032_hide_program_projects'),
        ('project_rates', '0002_remove_projectscore_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExpertAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='users.expert')),
                ('partner_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_expert_assignments', to='partner_programs.partnerprogram')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_assignments', to='projects.project')),
            ],
            options={
                'verbose_name': 'Назначение проекта эксперту',
                'verbose_name_plural': 'Назначения проектов экспертам',
                'indexes': [models.Index(fields=['partner_program', 'project'], name='project_rat_partner_85f175_idx'), models.Index(fields=['partner_program', 'expert'], name='project_rat_partner_aae584_idx')],
                'unique_together': {('partner_program', 'project', 'expert')},
            },
        ),
    ]
