# Generated by Django 4.2.11 on 2025-07-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="specialization",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="Специализация",
            ),
        ),
    ]
