# Generated by Django 4.2.11 on 2026-08-06 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_invitation_lifecycle(apps, schema_editor):
    """Сохраняет legacy-состояния и устраняет активные дубли до constraint."""
    Invite = apps.get_model("invites", "Invite")
    database = schema_editor.connection.alias
    seen_pending = set()
    changed = []

    invitations = (
        Invite.objects.using(database)
        .select_related("project")
        .all()
        .order_by("project_id", "user_id", "-datetime_created", "-id")
    )
    for invitation in invitations.iterator():
        invitation.invited_by_id = invitation.project.leader_id
        if invitation.is_accepted is not None:
            invitation.resolved_at = invitation.datetime_updated
        else:
            key = (invitation.project_id, invitation.user_id)
            if key in seen_pending:
                # Новейшее pending-приглашение остается активным, предыдущие
                # сохраняются в истории как отозванные.
                invitation.is_revoked = True
                invitation.resolved_at = invitation.datetime_updated
            else:
                seen_pending.add(key)
        changed.append(invitation)

    if changed:
        Invite.objects.using(database).bulk_update(
            changed,
            ["invited_by", "is_revoked", "resolved_at"],
            batch_size=500,
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("invites", "0002_invite_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_project_invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кем приглашен",
            ),
        ),
        migrations.AddField(
            model_name="invite",
            name="is_revoked",
            field=models.BooleanField(default=False, verbose_name="Отозвано"),
        ),
        migrations.AddField(
            model_name="invite",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата обработки"
            ),
        ),
        migrations.RunPython(
            populate_invitation_lifecycle,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="invite",
            index=models.Index(
                fields=["user", "is_accepted", "is_revoked", "datetime_created"],
                name="invite_user_state_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invite",
            index=models.Index(
                fields=["project", "is_accepted", "is_revoked", "datetime_created"],
                name="invite_project_state_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="invite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_accepted__isnull", True), ("is_revoked", False)),
                fields=("project", "user"),
                name="uniq_pending_project_invite",
            ),
        ),
        migrations.AddConstraint(
            model_name="invite",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_revoked", False), ("is_accepted__isnull", True), _connector="OR"
                ),
                name="invite_revoked_unaccepted",
            ),
        ),
    ]
