# Generated by Django 4.2.11 on 2026-09-29 12:08

from django.db import migrations, models
import django.db.models.deletion


def backfill_unambiguous_context(apps, schema_editor):
    Link = apps.get_model("partner_programs", "PartnerProgramProject")
    Invite = apps.get_model("invites", "Invite")
    database = schema_editor.connection.alias
    single_links = (
        Link.objects.using(database)
        .values("project_id")
        .annotate(link_count=models.Count("pk"), link_id=models.Min("pk"))
        .filter(link_count=1)
    )
    # Min здесь не выбирает победителя: count=1 доказывает единственность связи.
    for row in single_links.iterator():
        Invite.objects.using(database).filter(
            project_id=row["project_id"], program_link__isnull=True
        ).update(program_link_id=row["link_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("partner_programs", "0019_legacy_project_team_policy"),
        ("invites", "0003_legacy_pending_invite_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="program_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="team_invites",
                to="partner_programs.partnerprogramproject",
            ),
        ),
        migrations.RunPython(backfill_unambiguous_context, migrations.RunPython.noop),
    ]
