# Generated by Django 4.2.11 on 2026-08-15 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('project_invite_created', 'Приглашение в проект'), ('project_invite_accepted', 'Приглашение в проект принято'), ('project_invite_declined', 'Приглашение в проект отклонено'), ('project_invite_revoked', 'Приглашение в проект отозвано'), ('vacancy_response_created', 'Новый отклик на вакансию'), ('vacancy_response_accepted', 'Отклик принят'), ('vacancy_response_declined', 'Отклик отклонён'), ('team_invite_created', 'Приглашение в команду'), ('team_invite_accepted', 'Приглашение в команду принято'), ('team_invite_declined', 'Приглашение в команду отклонено'), ('team_invite_revoked', 'Приглашение в команду отозвано'), ('application_submitted', 'Заявка отправлена'), ('application_status_changed', 'Статус заявки изменён'), ('submission_submitted', 'Решение отправлено'), ('submission_status_changed', 'Статус решения изменён'), ('expert_assignment_created', 'Назначена экспертиза'), ('expert_assignment_revoked', 'Экспертиза отозвана'), ('evaluation_submitted', 'Оценка отправлена'), ('news_comment_created', 'Новый комментарий')], max_length=64)),
                ('category', models.CharField(choices=[('project', 'Проекты'), ('vacancy', 'Вакансии'), ('program', 'Программы'), ('expert', 'Экспертиза'), ('news', 'Новости'), ('system', 'Система')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('event_key', models.CharField(max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notif_rec_created_idx'), models.Index(fields=['recipient', 'read_at', '-created_at'], name='notif_rec_read_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient', 'event_key'), name='uniq_notification_recipient_event'),
        ),
    ]
