# Generated by Django 4.2.11 on 2026-09-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("project_invite_created", "Приглашение в проект"),
                    ("project_invite_accepted", "Приглашение в проект принято"),
                    ("project_invite_declined", "Приглашение в проект отклонено"),
                    ("project_invite_revoked", "Приглашение в проект отозвано"),
                    ("vacancy_response_created", "Новый отклик на вакансию"),
                    ("vacancy_response_accepted", "Отклик принят"),
                    ("vacancy_response_declined", "Отклик отклонён"),
                    ("program_news_published", "Новая новость программы"),
                    ("program_material_published", "Новый материал программы"),
                    ("course_access_opened", "Открыт доступ к курсу"),
                    ("team_invite_created", "Приглашение в команду"),
                    ("team_invite_accepted", "Приглашение в команду принято"),
                    ("team_invite_declined", "Приглашение в команду отклонено"),
                    ("team_invite_revoked", "Приглашение в команду отозвано"),
                    ("application_submitted", "Заявка отправлена"),
                    ("application_status_changed", "Статус заявки изменён"),
                    ("submission_submitted", "Решение отправлено"),
                    ("submission_status_changed", "Статус решения изменён"),
                    ("expert_assignment_created", "Назначена экспертиза"),
                    ("expert_assignment_revoked", "Экспертиза отозвана"),
                    ("evaluation_submitted", "Оценка отправлена"),
                    ("news_comment_created", "Новый комментарий"),
                ],
                max_length=64,
            ),
        ),
    ]
